config/routes.rb
require_relative '../app/resmap/rack/api_forwarder.rb'

ResmapRecon::Application.routes.draw do
  mount ::Resmap::Rack::ApiForwarder.new, at: '/rm'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :user

  resources :projects, only: [:index, :show, :new, :create] do
    member do
      get 'curate'
      get 'pending_changes'
      post 'dismiss_source_sites'
    end
    resources :sources, controller: 'project_sources', only: [:new, :index, :destroy] do
      resources :sites, controller: 'project_sources_sites', only: [] do
      end
      member do
        get 'source_list_details'
        get 'source_list_sites_with_mfl_id_csv'
        get 'unmapped_csv_download'
        post 'process_automapping'
        post 'reupload_source_list'

        get 'after_create'
        get 'invalid'
        get 'upload_new_file'

        resource 'import_wizard', controller: 'project_sources_import_wizard', only: [] do
          post 'validate'
          post 'start'
          get 'status'
        end
      end
      collection do
        get 'review_mapping'
        post 'create_from_file'
        post 'create_from_collection'
      end
    end
    resource :master, only: [] do
      get 'csv_download', controller: :project_master_sites
      get 'csv_download_from_rm', controller: :project_master_sites
      resources :sites, controller: 'project_master_sites', only: [] do
        collection do
          get 'index'
          post 'create'
          get 'search'
          get 'find_duplicates'
          get 'map'
        end
        member do
          post 'update'
          get 'consolidated_sites'
          get 'history'
        end
      end
    end
    resources :members, controller: 'project_members', only: [:index, :destroy, :create] do
      collection do
        get 'typeahead'
      end
    end
  end


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

end

app/controllers/project_sources_controller.rb
require 'csv'
class ProjectSourcesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_project

  def new
    @new_source_list ||= NewSourceList.new
    @source_list = SourceList.new project: @project
    master_name = @project.master_collection.name
    @collection_ids = AppContext.resmap_api.collections.all.select{|c| c.site_count > 0 && c.name != master_name}.map{|c| [c.name, c.id]}
  end

  def create_from_file
    @new_source_list = NewSourceList.new(params[:new_source_list])

    if @new_source_list.valid?
      @source_list = @new_source_list.create_in_project(@project)
      redirect_to after_create_project_source_path(@project, @source_list)
    else
      new
      render 'new'
    end
  end

  def create_from_collection
    source_list = SourceList.new project: @project, collection_id: params[:source_list][:collection_id] if params[:source_list] && params[:source_list][:collection_id].present?
    if source_list.present? && source_list.valid?
      source_list.save
      source_list.import_sites_from_resource_map
      redirect_to project_path(@project)
    else
      new
      render 'new'
    end
  end

  def after_create
    begin
      iw = @source.as_collection.import_wizard

      if iw.status == 'finished'
        return redirect_to source_list_details_project_source_path(@project, @source)
      end

      raise "invalid import wizard state: #{iw.status}" if iw.status != 'file_uploaded'
      @columns_spec = iw.guess_columns_spec
      @sites_to_import = iw.sites_count(@columns_spec)
    rescue
      redirect_to invalid_project_source_path(@project, @source)
    end
  end

  def upload_new_file
    @source.destroy
    redirect_to new_project_source_path(@project)
  end

  def source_list_details
    begin
      @new_source_list = NewSourceList.new name: @source.as_collection.name
      if @source.as_collection.import_wizard.status == 'file_uploaded'
        redirect_to after_create_project_source_path(@project, @source)
      end

      if @source.site_mappings.count == 0
        @source.import_sites_from_resource_map
      end

      @curation_progress = @source.curation_progress
      @mapping_progress = @source.mapping_progress
    rescue Exception => e
      redirect_to invalid_project_source_path(@project, @source)
    end
  end

  def invalid
    @new_source_list = NewSourceList.new name: @source.name
  end

  def index
    res = @project.source_lists.map do |s|
      h = s.as_json
      h["name"] = s.name
      h
    end

    render json: res
  end

  def source_list_sites_with_mfl_id_csv
    csv_string = @source.sites_with_mfl_id_csv
    send_data(csv_string, :type => 'text/csv; charset=utf-8; header=present', :filename => "#{@source.name}")
  end

  def unmapped_csv_download
    csv_string = @source.unmapped_sites_csv
    send_data(csv_string, :type => 'text/csv; charset=utf-8; header=present', :filename => "#{@source.name}")
  end

  def process_automapping
    # corrections = flatten_corrections(params[:corrections]) || {}
    # error_tree, count = @source.process_automapping(params[:chosen_fields], corrections)
    error_tree, count = @source.process_automapping(params[:chosen_fields])
    render json: {error_tree: error_tree, count: count, mapping_progress: @source.mapping_progress}
  end

  def reupload_source_list
    @original_source = SourceList.find(params[:id])
    @original_source.as_collection.destroy
    @original_source.destroy

    @new_source_list = NewSourceList.new(params[:new_source_list])
    if @new_source_list.valid?
      @source_list = @new_source_list.create_in_project(@project)
    end

    redirect_to after_create_project_source_path(@project, @source_list)
  end

  def destroy
    @source.destroy
    redirect_to project_path(@project)
  end

  protected

  def load_project
    @project = load_project_by_id(params[:project_id])
    @source = @project.source_lists.find(params[:id]) if params[:id].present?
  end

  # def flatten_corrections(error_tree, corrections={})
  #   return unless error_tree
  #   corrections ||= {}
  #   error_tree.each do |branch|
  #     corrections[branch[:name]] = branch[:correction] if branch[:correction]
  #     corrections[branch[:name]] = branch[:fixed] if branch[:fixed]
  #     corrections.merge!(flatten_corrections(branch[:sub], corrections)) if branch[:sub]
  #   end
  #   corrections
  # end

end

app/views/project_sources/_hidden_reupload_form.haml
.hide
  = simple_form_for new_source_list, url: reupload_source_list_project_source_path(project), html: { id: 'reupload-form' } do |f|
    = f.input :name, as: :hidden
    = f.input :file, wrapper_html: {id: 'reupload-field'}, input_html: {onchange: 'this.form.submit();'}

app/views/project_sources/after_create.html.haml
= back_to_project

%h1
  = @source.name

.row-fluid
  .span4
    %p
      .badge.badge-info
        = @sites_to_import
      facilities to import

    %div{'ng-app'=>'ProjectSourceAfterCreateApp', 'ng-init'=>init_scope(project_id: @project.id, source_id: @source.id, columns_spec: @columns_spec)}

      %div(ng-controller='AfterCreateCtrl')

        %fieldset
          .control-group(ng-class='{error: !valid_columns_spec}')
            %label.control-label Data source identifier:
            .controls
              %select(ng-model='identifier_column' ng-options='cs.header for cs in columns_spec')
              %span.help-inline(ng-show='valid_columns_loading')
                Validating...
              %span.help-inline(ng-show='!valid_columns_spec && validation_errors.length == 0')
                This column can't be used as identifier
              %span.help-inline(ng-show='!valid_columns_spec && validation_errors.length > 0')
                ResourceMap validation error: {{validation_errors}}
              
        %button.btn.btn-primary(ng-disabled="import_disabled" ng-click="import()" ladda-loading="importing" ng-hide="status_finished")
          Import

        = link_to project_source_path(@project, @source), :method => :delete, "class" => 'btn afterCreate', "ng-show" => "!status_finished" do
          Delete

        = link_to upload_new_file_project_source_path(@project, @source), :method => :get, "class" => 'btn afterCreate', "ng-show" => "!status_finished" do
          Upload new list


        %p(ng-show="status_finished")
          Facilities imported. You will be redirected in {{redirect_in}} seconds or
          %a(ng-href='{{redirect_url}}')
            click here
          \.
  .span4
    .alert.alert-info
      The source is almost ready.
      %br
      Select the identifier field.
      %br
      Click
      %b Import
      when ready.

app/views/project_sources/invalid.haml
.row-fluid
  .span9
    %div
      = back_to_project
      %h1
        = @source.name

    %div
      %p There was a problem with this source list's upload. Please ensure you upload a valid CSV file.

      %p
        %a.btn.btn-large{onclick: "$('#reupload-field input').click()"}
          %i.icon-upload
          Upload new version

        = link_to project_source_path(@project, @source), :method => :delete, class: 'btn btn-large' do
          %i.icon-trash
          Delete


= render partial: 'hidden_reupload_form', locals: {new_source_list: @new_source_list, project: @project}

app/views/project_sources/mapping_property_not_set.html.haml
= link_to '← back to source list', source_list_details_project_source_path(@project, @source)

.row-fluid
  .span9
    %h1 Not ready

    %p You must start with the facilities mapping first.

app/views/project_sources/new.html.haml
= back_to_project

%h1
  New facility source
  
%p Choose a name for the list and upload it.  

%p
  = link_to "Download a sample csv here", "/sample_source_list.csv"

%br
.row-fluid
  .span4
    = simple_form_for @new_source_list, url: create_from_file_project_sources_path(@project) do |f|

      
      = f.input :name
      = f.input :file, label: 'File (.csv documents only)'

      = submit_ladda_button 'Upload & continue'

    %a.muted(href='#advanced' data-toggle='collapse') advanced

    #advanced.collapse
      = simple_form_for @source_list, url: create_from_collection_project_sources_path(@project) do |f|
        Or choose an existing ResourceMap collection
        = f.input :collection_id, collection: @collection_ids

        = submit_ladda_button 'Create & continue'

  .span4
    .alert.alert-info
      Each source list must have the following:
      %br
      %br
      %div
        1. A field titled "Name" for the facility name.
      %div
        2. A field with a unique identifier.
      %div
      3. Individual fields for each level of the admin hierarchy (i.e., Region, District, etc.). 
      %br
      %br
      Also, make sure that the source list administrative hierarchy matches the MFL hierarchy.

app/views/project_sources/source_list_details.html.haml
%div{'ng-app'=>'MappingEditorApp', 'ng-init'=> init_scope(project_id: @project.id, source_list_id: @source.id, source_field_options: @source.as_collection.fields.map{|f| {name: f.name, id: f.code}}.select{|h| !h[:name].starts_with?("_")}, hierarchy: @project.required_hierarchy, percentage_classified: @mapping_progress, site_count: @source.site_mappings.count)}
  - angular_templates 'shared/angular'

  .row-fluid
    .span9
      %div{'ng-controller' => 'MappingEditorCtrl'}
        = back_to_project
        %h1
          = @source.name

        = link_to unmapped_csv_download_project_source_path(@project, @source), class: "btn btn-large" do
          %i.icon-download-alt
          Export not mapped data

        %span

        %a.btn.btn-large{'ng-click' => 'reupload()'}
          %i.icon-upload
          Upload new version

        %h2 Facilities Mapping

        = "#{@curation_progress || 0}% curated, "
        {{(percentage_classified | number) || 0}}%
        mapped

        .progress
          .bar.bar-success{style: "width: #{@curation_progress}%"}
          .bar{style: "width: {{percentage_classified - #{@curation_progress}}}%"}

        .span9
          %table.table.table-bordered
            %thead
              %th Admin Level
              %th Source Field to Map
            %tbody
              %tr{'ng-repeat' => 'level in hierarchy_levels', 'style' => 'vertical-align:middle'}
                %td
                  Level {{$index + 1}} (e.g. {{level.name}})
                %td
                  / %select{'ng-model' => 'level.option', 'ng-options' => 'option.name group by option.kind for option in level.options', 'ng-change' => 'recompute_hierarchy_levels($index)'}
                  %select{'ng-model' => 'level.option', 'ng-options' => 'option.name for option in level.options', 'ng-change' => 'check_if_complete()'}

          %div
            This process can take a few minutes, please be patient.

          %br

          .map-button.pull-right
            %span{'ng-show' => '!all_fields_chosen'} Choose a value or a field for every level
            %button.btn.btn-primary{'ng-click' => 'process_automapping()', 'ladda-loading' => 'loading_error_tree', 'ng-disabled' => '!all_fields_chosen'} Map


        .span9{'ng-show' => 'mapped_count != undefined'}
          %h3 Hierarchy mapping results

          %span{'ng-show' => 'site_count - mapped_count == 1'}
            {{site_count - mapped_count}} site could not be matched to hierarchy. No mappings were done.
          %span{'ng-show' => 'mapped_count < site_count && site_count - mapped_count != 1'}
            {{site_count - mapped_count}} sites could not be matched to hierarchy. No mappings were done.
          %span{'ng-show' => 'mapped_count == site_count'}
            All {{mapped_count}} sites were mapped!

        .span9#mapping-errors-tree{'ng-show' => 'mapped_count != undefined && mapped_count != site_count'}
          %h3 Hierarchy mapping errors
          %div{'ng-show' => 'error_tree == undefined'} No conflicts yet! Select fields and press map to start automapping
          .row-fluid{'ng-show' => 'error_tree != undefined'}
            .span6
              %h4 Source Hierarchy
              Some values do not map to the MFL, select a different field to map or edit and re-load your source list
            .row-fluid
              .span12
                %hr
              .span12
                %ul
                  %li(ng-repeat='node in error_tree' ng-include="'error_tree_node.html'")

    .span3
      .well
        .row-fluid
          .span12
            %span.huge
              = @source.site_mappings.count
            %span
              facilities

        %br

        .row-fluid
          .span12
            = link_to 'view in resourcemap →', @source.as_collection.show_url, target: '_blank'

= render partial: 'hidden_reupload_form', locals: {new_source_list: @new_source_list, project: @project}