config/routes.rb
require_relative '../app/resmap/rack/api_forwarder.rb'

ResmapRecon::Application.routes.draw do
  mount ::Resmap::Rack::ApiForwarder.new, at: '/rm'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :user

  resources :projects, only: [:index, :show, :new, :create] do
    member do
      get 'curate'
      get 'pending_changes'
      post 'dismiss_source_sites'
    end
    resources :sources, controller: 'project_sources', only: [:new, :index, :destroy] do
      resources :sites, controller: 'project_sources_sites', only: [] do
      end
      member do
        get 'source_list_details'
        get 'source_list_sites_with_mfl_id_csv'
        get 'unmapped_csv_download'
        post 'process_automapping'
        post 'reupload_source_list'

        get 'after_create'
        get 'invalid'
        get 'upload_new_file'

        resource 'import_wizard', controller: 'project_sources_import_wizard', only: [] do
          post 'validate'
          post 'start'
          get 'status'
        end
      end
      collection do
        get 'review_mapping'
        post 'create_from_file'
        post 'create_from_collection'
      end
    end
    resource :master, only: [] do
      get 'csv_download', controller: :project_master_sites
      get 'csv_download_from_rm', controller: :project_master_sites
      resources :sites, controller: 'project_master_sites', only: [] do
        collection do
          get 'index'
          post 'create'
          get 'search'
          get 'find_duplicates'
          get 'map'
        end
        member do
          post 'update'
          get 'consolidated_sites'
          get 'history'
        end
      end
    end
    resources :members, controller: 'project_members', only: [:index, :destroy, :create] do
      collection do
        get 'typeahead'
      end
    end
  end


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend Memoist
  include Configurable

  has_many :user_project_memberships
  has_many :users, through: :user_project_memberships,
    before_add: :ensure_resmap_user_membership,
    before_remove: :revoke_resmap_user_membership

  has_many :source_lists,
    before_add: :ensure_resmap_memberships

  attr_accessible :config, :name
  validates :name, :presence => true

  default_scope order('name')

  config_property :master_collection_id
  config_property :master_collection_target_field_id

  serialize :hierarchy, MarshalZipSerializable

  BASIC_FIELDS = [
    { name: 'Facility Code', code: 'fcode', kind: 'text' },
    { name: 'Facility Type', code: 'ftype', kind: 'text' },
    { name: 'Beds', code: 'beds', kind: 'numeric' }
  ]

  class NoHierarchyDefinedError < StandardError; end

  def has_facilities?
    master_collection.sites.count > 0
  end

  def master_collection
    AppContext.resmap_api.collections.find(master_collection_id)
  end
  memoize :master_collection

  def target_field_defined?
    begin
      target_field
      true
    rescue NoHierarchyDefinedError
      false
    end
  end

  def target_field
    if master_collection_target_field_id
      master_collection.field_by_id(master_collection_target_field_id)
    else
      pull_hierarchy_field || raise(NoHierarchyDefinedError)
    end     
  end

  def required_hierarchy
    unless self.hierarchy    
      pull_hierarchy_field || raise(NoHierarchyDefinedError)
    end

    self.hierarchy
  end

  def source_collections
    source_lists.map &:as_collection
  end

  def source_collection_by_id(id)
    source_collections.detect { |c| c.id == id }
  end

  def pending_changes(source_list_id, node_id, search, page)
    node_ids = node_id ? search_node_ids_under(node_id) : nil

    #TODO: receive which source list to use from client
    l = source_lists.find(source_list_id) || []

    res = l.pending_changes(node_ids, search, page)

    if res[:headers].present?
      res[:headers_array] = []

      res[:headers].each_pair do |code, name|
        res[:headers_array].push({ code: code, name: name })
      end

      res[:headers] = res.delete(:headers_array)
    else
      res[:headers] = []
    end

    res
  end

  def search_node_ids_under(node_id, nodes = hierarchy)
    nodes.each do |node|
      if node["id"] == node_id
        return gather_children_ids(node)
      elsif node["sub"]
        result = search_node_ids_under(node_id, node["sub"])
        return result if result
      end
    end
    nil
  end

  def gather_children_ids(node, ids = [])
    ids << node["id"]
    if node["sub"]
      node["sub"].each do |sub|
        gather_children_ids sub, ids
      end
    end
    ids
  end

  def consolidated_with(master_site_id)
    source_lists.flat_map { |s| s.consolidated_with(master_site_id) }
  end

  def dismiss_source_site(source_list_id, site_id)
    source_lists.find(source_list_id).dismiss_site(site_id)
  end

  def revoke_resmap_user_membership(user)
    email = user.email

    master_collection.members.find_or_create_by_email(email).delete!
    source_lists.each do |s|
      s.as_collection.members.find_or_create_by_email(email).delete!
    end
  end

  def ensure_resmap_user_membership(user)
    ensure_membership_permissions user: user
  end

  def ensure_resmap_memberships(source_list)
    ensure_membership_permissions source_list: source_list
  end

  def ensure_membership_permissions(options)
    users_to_add = options.has_key?(:user) ? [options[:user]] : self.users
    source_lists_to_add = options.has_key?(:source_list) ? [options[:source_list]] : self.source_lists

    users_to_add.each do |user|
      self.master_collection.members.find_or_create_by_email(user.email).set_admin!
      source_lists_to_add.each do |s|
        s.as_collection.members.find_or_create_by_email(user.email).set_admin!
      end
    end
  end

  def mfl_mapping_progress
    unmapped_mfl_sites_count / self.master_collection.site_count
  end

  def unmapped_mfl_sites_count
    search_mfl(page_size: 2, hierarchy: "").total_count
  end

  def unmapped_mfl_sites?
    unmapped_mfl_sites_count > 0    
  end

  def search_mfl(options={})
    page_size = options[:page_size] || 50
    page = options[:page] || 1
    search = options[:search] || {}
    hierarchy = options[:hierarchy]

    sites = self.master_collection.sites

    if search.empty? && !hierarchy
      sites = sites.where({})
    else
      sites = sites.where(search: search) unless search.empty?
      sites = sites.where("#{self.target_field.code}[under]" => hierarchy) if hierarchy
    end

    sites.page_size(page_size).page(page)
  end

  def app_suffix
    "#{Settings.system_id}_#{id}"
  end

  def app_layer_name
    "_recon_tool_#{app_suffix}_"
  end

  def app_seen_field_name
    "_seen_#{app_suffix}_"
  end

  def app_master_site_id
    "_master_site_id_#{app_suffix}_"
  end

  private

  def pull_hierarchy_field
    master_collection.reload
    hierarchy_field = master_collection.field_by_code('admin_division')

    if hierarchy_field && hierarchy_field.id
      self.master_collection_target_field_id = hierarchy_field.id
      self.hierarchy = YAML.load(hierarchy_field.hierarchy.to_yaml)
      self.save!
      hierarchy_field
    else
      nil
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_project, except: [:index, :new, :create]
  before_filter :setup_templates, only: [:new, :create]

  def index
    @projects = current_user.projects
  end

  def show
    # Force all collections to be loaded at once, to avoid subsequent N+1 requests
    cols = AppContext.resmap_api.collections.all

    @source_lists = @project.source_lists.map do |source_list|
      c = cols.detect { |c| c.id == source_list.collection_id }      
      name = c.nil? ? 'Undefined' : c.name

      {
        name: name,
        model: source_list
      }
    end

    @curation_progress = "#{@project.source_lists.map(&:curation_progress).reduce(:+) / @project.source_lists.count}%" rescue "0%"
  end

  def curate
    @hierarchy_field_id = @project.target_field.id
    @pending_changes_site_list = unify(@project.source_lists.map(&:mapped_hierarchy_counts))
    @source_lists = @project.source_lists.map do |s|
      h = s.as_json
      h["name"] = s.name
      h["headers"] = Hash[s.as_collection.fields.map { |field| [field.code, field.name] }]
      h
    end
    @source_lists.insert 0, { "name" => "All sources" }
  end

  def pending_changes
    page = 1
    page = params[:page] if params[:page].present?

    changes = @project.pending_changes(params[:source_list_id], params[:target_value], params[:search].presence, page)

    data = { sites: changes[:sites], headers: changes[:headers], current_page: changes[:current_page], total_count: changes[:total_count] }

    render json: data
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(name: params[:project][:name])

    if @project.valid?
      apply_template(@project, params[:project][:template])
      @project.users << current_user
      @project.save!

      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def dismiss_source_sites
    project = Project.find(params[:id])
    params[:source_sites].each do |site|
      source_list = project.source_lists.find(site[:source_list_id])
      source_list.dismiss_site(site[:id])
    end

    render nothing: true
  end

  protected

  def setup_templates
    @templates = ['Kenya MFL', 'Tanzania MFL', 'Other Country']
  end

  def apply_template(project, template)
    collection = AppContext.resmap_api.collections.create name: project.name

    fields_to_create = Project::BASIC_FIELDS.dup

    unless template == 'Other Country'
      raw_hierarchy = HierarchyTemplate.load(template)
      hierarchy = prepare_hierarchy(raw_hierarchy)
      fields_to_create.push({ name: 'Administrative Division', code: 'admin_division', kind: 'hierarchy', config: { hierarchy: hierarchy } })
      project.hierarchy = raw_hierarchy
    end

    layer = collection.find_or_create_layer_by_name 'Main'

    layer.ensure_fields fields_to_create

    project.master_collection_id = collection.id

    project.master_collection_target_field_id = collection.field_by_code('admin_division').id unless template == 'Other Country'
  end

  def prepare_hierarchy(hierarchy)
    res = []
    hierarchy.each_with_index do |n,i|
      res[i] = { 'id' => n['id'], 'name' => n['name'] }
      res[i]['sub'] = prepare_hierarchy(n['sub']) unless n['sub'].nil?
    end

    res
  end

  protected

  def load_project
    @project = load_project_by_id(params[:id])
  end

  def unify(mapped_counts)
    unified = {}
    unified.default = 0
    mapped_counts.each do |counts|
      counts.each do |k,v|
        unified[k] += v
      end
    end
    unified
  end

end

app/views/projects/_display_sites_fields.html.haml
%td(dnd-source='site.name') {{site.name}}
%td(dnd-source='site.source_list.name') {{site.source_list.name}}

%td{'ng-repeat'=>'(code,name) in headers', 'dnd-source' => 'value'} {{site.properties[code]}}

app/views/projects/_merge_sites.html.haml
.row-fluid#merge-panel
  .span8#source-sites-container
    .source-list{'ng-repeat' => '(source_id, source_sites) in merge_source_sites'}
      %legend {{ source_name(source_id) }}
      .source{'ng-repeat' => 'source_site in source_sites'}
        %div
          %label Facility Name
          %span(dnd-source='source_site.name') {{source_site.name}}

        %label Latitude & Longitude
        .input-append
          %span.input-small(dnd-source='source_site.lat') {{ source_site.lat }}
          %span.input-small(dnd-source='source_site.long') {{ source_site.long }}
          %button.btn(location-edit editable='false' latitude='source_site.lat' longitude='source_site.long')
            %i.icon-globe


        %div{'ng-repeat'=>'(key, value) in source_site.properties'}
          %label {{header_for(source_site, key)}}
          %span(dnd-source='value') {{value}}

  .span4
    %fieldset(ng-disabled='viewing_reconciliations')
      %legend Master Facility

      .control-group(ng-class='{error: merge_mfl_site.duplicate}')
        %label Facility Name
        %input(type='text' ng-model='merge_mfl_site.name' dnd-target='merge_mfl_site.name' ng-change='check_for_duplicate(merge_mfl_site.name)')
        %span.help-inline(ng-show='merge_mfl_site.duplicate') There already is a facility with this name in this district

      .control-group
        %label Administrative Division
        %hierarchy-input{collection_id: @project.master_collection_id, field_id: @project.target_field.id, node_id: "merge_mfl_site.properties.#{@project.target_field.code}"}

      .control-group
        %label Latitude & Longitude
        .input-append
          %input.input-small(type='text' ng-model='merge_mfl_site.lat' dnd-target='merge_mfl_site.lat')
          %input.input-small(type='text' ng-model='merge_mfl_site.long' dnd-target='merge_mfl_site.long')
          %button.btn(location-edit latitude='merge_mfl_site.lat' longitude='merge_mfl_site.long')
            %i.icon-globe

      - @project.master_collection.fields.each do |field|
        - if field.id != @project.master_collection_target_field_id
          .control-group{'ng-class' => "{error: has_errors(\"#{field.id}\")}"}
            %label= field.name
            %input{'type'=>'text', 'ng-model'=>"merge_mfl_site.properties.#{field.code}", 'dnd-target' =>"merge_mfl_site.properties.#{field.code}"}
            %br
            %label{'class' => 'control-label', 'has-error'=>'', 'ng-show' => "has_errors(\"#{field.id}\")"}
              = "{{error_message(\"#{field.id}\")}}"


      %button.btn.btn-inverse(ng-click='consolidate()' ladda-loading='consolidate_loading' ng-disabled='merge_mfl_site.duplicate' ng-show='!viewing_reconciliations')
        Save & Consolidate
      / %br
      / %span
      /   with {{source_site.name}}

app/views/projects/_other_consolidations.html.haml
%h2 Other consolidations

%div(ng-show='target_site.id == null')
  Not applicable. You are creating a new site in the MFL.

%div(ng-show='target_site.id != null && consolidated_sites == null')
  Loading past consolidations...

%div.recon-panel(ng-show='consolidated_sites != null')
  %p(ng-show='consolidated_sites.length == 0')
    There are no consolidations

  .accordion-group(ng-repeat='site in consolidated_sites')
    .accordion-body.selected
      .accordion-inner
        .badge.label-warning{'ng-show'=>"site.pending"} Pending
        .badge.label-success{'ng-show'=>"site.id == source_site.id"} Selected
        = render 'projects/display_sites_fields'

app/views/projects/_pending_list.html.haml
%div(ng-controller='PendingListCtrl')
  %ul.unstyled
    %li(ng-repeat='node in list')
      %a.unstyled(ng-click='choose(node)' href='javascript:')
        {{node.path}}
        ({{node.id}})
        %span.badge {{node.count}}

app/views/projects/_search_master_site.html.haml
%div.input-append(ng-controller='SearchSiteCtrl' ng-show='target_site == null')
  %input.input-large{'type' => 'text', 'ng-model' => 'search'}
  %span.add-on
    %i.icon-search



%br

app/views/projects/_search_source_records.haml
%div.input-append(ng-controller='SearchSourceRecordsCtrl')
	%input.input-large{'type' => 'text', 'ng-model' => 'search'}
	%span.add-on
		%i.icon-search
	

app/views/projects/_source_lists.html.haml
%ul.project_source_lists
  - @source_lists.each do |source_list|
    %li
      .well.well-small.well-white
        = link_to source_list[:name], source_list_details_project_source_path(@project, source_list[:model])
        %br
        = link_to "Download with MFL ID", source_list_sites_with_mfl_id_csv_project_source_path(@project, source_list[:model])
        %br
        %br
        .source-bottom
          - source_list[:model].mapping_progress.tap do |progress|
            - if progress == 100
              %i.icon-ok
            - else
              %i.icon-warning-sign
            = "#{progress}% mapped"
            .progress
              .bar{style: "width: #{progress}%"}


  %li
    .well.well-small
      %a{href: new_project_source_path(@project)}
        %i.icon-plus-sign
        %br
        New facility source

app/views/projects/curate.html.haml
%div{'ng-app'=>'CurationApp', 'ng-init'=> init_scope(project_id: @project.id, hierarchy_field_id: @hierarchy_field_id, app_master_site_id: @project.app_master_site_id, hierarchy_target_field_code: @project.target_field.code, pending_list: @pending_changes_site_list, source_lists: @source_lists, master_collection_id: @project.master_collection.id)}
  - angular_templates 'shared/angular'

  %div(ng-controller='CurationPanel')
    .row-fluid(ng-hide='merging')
      .span3
        = back_to_project
        %rm-collection-context(id="#{@project.master_collection.id}")
          %h3 Administrative Unit
          %rm-hierarchy-tree{collection_id: "collection_id", field_id: @hierarchy_field_id, node_template: "hierarchy_tree_node.html", pending_list: "pending_list"}

      .span9
        .row-fluid
          .span12
            .span12
              %h3.same-line-title Source List:
              %mfl-source-list-combo{'mfl-source-lists' => 'source_lists', 'mfl-selection-changed' => 'source_list_changed(new_selected_source_list)', 'mfl-selected-item' => 'selected_source_list'}

              .right-search
                = render 'search_source_records'

            .recon-panel{'ng-repeat' => 'source in selected_source_lists'}
              %h5 {{ source.name }}
              %mfl-grid{'mfl-data-source' => 'source_sites[source.id]', 'mfl-page-changed' => 'page_changed(source.id, new_page)', 'mfl-multiple-selection' => 'true', 'mfl-selection-changed' => 'selection_changed(source.id, selected_items)'}

              .row-fluid
                .well(ng-show='!source_sites_loading[source.id] && source_sites[source.id].items.length == 0')
                  There are no facilities to curate on list {{source.name}}

        .row-fluid
          .span12
            %a.btn.btn-primary(href='javascript:' ng-click='open_merge()' ng-disabled='empty_source_or_target()')
              %i.icon-circle-arrow-right.icon-white
              Merge
            %a.btn.btn-primary(href='javascript:' ng-click='create_target_site()' ng-disabled='source_site_empty()')
              %i.icon-plus-sign.icon-white
              Create new site in MFL
            %a.btn.btn-warning(href='javascript:' ng-click='dismiss()' ng-disabled='source_site_empty()')
              %i.icon-remove-sign.icon-white
              Dismiss
            %a.btn.btn-primary(ng-click='view_reconciliations()' ng-disabled='!target_mfl_site')
              %i.icon-eye-open.icon-white
              View Reconciliations

        .row-fluid
          .span12
            .span12
              %h3.same-line-title Master List
              .right-search
                = render 'search_master_site'

            .recon-panel
              %mfl-grid{'mfl-data-source' => 'mfl_sites', 'mfl-page-changed' => 'mfl_page_changed(new_page)', 'mfl-selection-changed' => 'mfl_selection_changed(selected_items[0])'}

              .row-fluid
                .well(ng-show='mfl_sites.items.length == 0')
                  There are no facilities in the master list

    %div(ng-controller='MergePanel' ng-show='merging')
      .row-fluid
        .span12
          %a(href='javascript:' ng-click='close_merge()') ← back to grid

      = render 'merge_sites'

app/views/projects/index.html.haml
%h1 Projects

.row
  .span4
    %ul.nav.nav-tabs.nav-stacked
      - @projects.each do |p|
        %li
          = link_to project_path(p) do
            = p.name
            %i.icon-chevron-right.pull-right

      %li
        = link_to new_project_path do
          %i.icon-plus
          Create project

  .span8
    .alert.alert-info
      Thank you for your interest.
      %br
      %br
      This is a prototype tool that was started around the problem of how to map, link and consolidate multiple facility lists that lack a common identifier.   It is yet to be extensively beta-tested among users, so please keep a few things in mind as you get started: 

      %br
      %br

      %ul
        %li This is a prototype tool - there will be bugs and you will probably run into technical issues. If you find a bug or have a request for new features please share them by sending an email to masterfacilitylist@googlegroups.org.
        %li There will be design and user interface elements that may be annoying; be sure to share them in the group above so that everyone can learn about the particular needs of your organization and patterns in your data.

      %br
      
      Having up-to date facility lists is valuable information, that leads to better health systems management and ultimately better service delivery. Hopefully this tool will help you consolidate such important data for your country. 

app/views/projects/new.html.haml
%h1 New curation project

= simple_form_for @project do |f|
  = f.input :name

  = f.input :template, as: :radio_buttons, collection: @templates, checked: @templates.first

  .control-group
    = submit_ladda_button 'Create'
    = link_to 'Cancel', projects_path, class: 'btn btn-link'

app/views/projects/show.html.haml
.row-fluid

  .span9
    %h2 Step 1. Define MFL Schema

    .row-fluid
      .span6
        %p
          = link_to 'Review MFL Schema in Resource Map →', @project.master_collection.layers_url, target: '_blank'
        - if @project.master_collection.site_count == 0
          %p
            = link_to "Import initial MFL data using Resource Map's Import Wizard →", @project.master_collection.import_wizard_url, target: '_blank'

    %h2 Step 2. Import and  Map Source List
    Note: Unmapped records can't be reconciled in Step 3

    %br
    %br

    = render 'source_lists'

    %h2 Step 3. Reconciled Facility Data
    = "#{@curation_progress} reconciled"
    .progress
      .bar{style: "width: #{@curation_progress}"}
    %p
      = link_to 'Reconcile Source Lists', curate_project_path(@project)

    %h2 Step 4. Export MFL

    %p
      = link_to 'Review and Edit MFL Data', project_master_sites_path(@project)
    %p
      = link_to 'Download a PROMIS .csv', csv_download_project_master_path(@project)
    %p
      = link_to 'Download Master Facility List', csv_download_from_rm_project_master_path(@project)

  .span3
    .well
      .row-fluid
        .span12
          %span.huge
            = @project.master_collection.sites.count
          %span
            master facilities
      %br
      .row-fluid
        .span12
          %span.huge
            = @project.users.count
          %span
            members collaborating

      %br

      / %p
      /   = link_to "Recent activity", "http://resmap-stg.instedd.org/activity", target: '_blank'
      %p
        = link_to 'View mfl in resource map →', @project.master_collection.show_url, target: '_blank'
      %p
        = link_to 'Invite user to collaborate', project_members_path(@project)