config/routes.rb
require_relative '../app/resmap/rack/api_forwarder.rb'

ResmapRecon::Application.routes.draw do
  mount ::Resmap::Rack::ApiForwarder.new, at: '/rm'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :user

  resources :projects, only: [:index, :show, :new, :create] do
    member do
      get 'curate'
      get 'pending_changes'
      post 'dismiss_source_sites'
    end
    resources :sources, controller: 'project_sources', only: [:new, :index, :destroy] do
      resources :sites, controller: 'project_sources_sites', only: [] do
      end
      member do
        get 'source_list_details'
        get 'source_list_sites_with_mfl_id_csv'
        get 'unmapped_csv_download'
        post 'process_automapping'
        post 'reupload_source_list'

        get 'after_create'
        get 'invalid'
        get 'upload_new_file'

        resource 'import_wizard', controller: 'project_sources_import_wizard', only: [] do
          post 'validate'
          post 'start'
          get 'status'
        end
      end
      collection do
        get 'review_mapping'
        post 'create_from_file'
        post 'create_from_collection'
      end
    end
    resource :master, only: [] do
      get 'csv_download', controller: :project_master_sites
      get 'csv_download_from_rm', controller: :project_master_sites
      resources :sites, controller: 'project_master_sites', only: [] do
        collection do
          get 'index'
          post 'create'
          get 'search'
          get 'find_duplicates'
          get 'map'
        end
        member do
          post 'update'
          get 'consolidated_sites'
          get 'history'
        end
      end
    end
    resources :members, controller: 'project_members', only: [:index, :destroy, :create] do
      collection do
        get 'typeahead'
      end
    end
  end


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

end

app/controllers/project_members_controller.rb
class ProjectMembersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_project

  def index
  end

  def create
    begin
      email = params[:member][:email]

      invited = User.by_email(email)
      @project.users << invited

      flash.notice = "#{email} added to project"
    rescue
      flash[:error] = "Couldn't add #{email} to this project. Please ensure there's an active MFL user with that email. For a user to be active, they must have created an account and confirmed their email address."
    end

    redirect_to project_members_path(@project)
  end

  def destroy
    user = @project.users.find(params[:id])
    @project.users.delete user
    flash.notice = "#{user.email} removed from project"

    if user == current_user
      redirect_to projects_path
    else
      redirect_to project_members_path(@project)
    end
  end

  def typeahead
    render json: @project.master_collection.members.invitable(params[:q])
  end


  protected

  def load_project
    @project = load_project_by_id(params[:project_id])
  end
end

app/views/project_members/index.html.haml
= back_to_project

%h1 Members

.row-fluid
  .span6
    %table.table.table-bordered
      %tr
        %th Email
        %th
      - @project.users.each do |user|
        %tr
          %td= user.email
          %td
            - unless @project.users.count == 1 && user == current_user
              = link_to 'Remove', project_member_path(@project, user), method: :delete, class: 'ladda'

%h2 Invite members

= form_for :member, html: { class: 'form-inline add-members' } do |f|
  = f.text_field :email, class: 'input', placeholder: 'Email', autocomplete: 'off'
  = submit_ladda_button 'Add'

:javascript
  $(function(){
    $('.add-members input[name="member[email]"]').
      typeahead({
        source: function (query, process) {
          $.get("/projects/#{@project.id}/members/typeahead", {q: query},
            function(data){ process(data); });
        }
      });
  });